name: CI

on:
  push:
    branches:
      - main
  pull_request:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  test:
    name: ${{ matrix.python-version }}-build
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.9", "3.10", "3.11", "3.12"]
    steps:
      - uses: actions/checkout@v4
      - name: Install Conda environment from environment.yml
        uses: mamba-org/setup-micromamba@v1
        with:
          environment-name: carbonplan
          condarc: |
            channels:
              - conda-forge
              - nodefaults
          cache-downloads: false
          cache-environment: true
          create-args: >-
            python=${{ matrix.python-version }}
      - name: Install package
        run: |
          python -m pip install -e .[dev]
      - name: Conda list information
        run: |
          conda env list
          conda list
      - name: Run tests
        run: |
          python -m pytest --junitxml=test-reports/junit.xml --cov=./ --verbose
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v3.1.1
        with:
          file: test-reports/junit.xml
